name: MCP Server CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.17.0"
          otp-version: "26.2.1"

      - name: Cache Mix dependencies
        uses: actions/cache@v4
        with:
          path: |
            mcp_server/deps
            mcp_server/_build
          key: ${{ runner.os }}-mix-${{ hashFiles('mcp_server/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Install dependencies
        run: |
          cd mcp_server
          mix local.hex --force
          mix local.rebar --force
          mix deps.get

      - name: Build
        run: |
          cd mcp_server
          mix compile --warnings-as-errors

      - name: Run tests
        run: |
          cd mcp_server
          mix test
